In [5]:
import pandas as pd

In [10]:
path = "C:/Users/vihaa/Desktop/Solar Panel/Solar Panel Fault Detection"

path = r"C:\Users\vihaa\Desktop\Solar Panel\Solar Panel Fault Detection
unicodeescape

In [11]:
solar = pd.read_csv(path + "/backend/data/timeseries/raw/Solar_Energy_Generation.csv")
weather=pd.read_csv(path+"/backend/data/timeseries/raw/Weather_Data_reordered_all.csv")

In [17]:
print(solar.head())
solar.shape

   CampusKey  SiteKey            Timestamp  SolarGeneration
0          2        1  2020-01-01 00:15:00              NaN
1          2        1  2020-01-01 00:30:00              NaN
2          2        1  2020-01-01 00:45:00              NaN
3          2        1  2020-01-01 01:00:00              NaN
4          2        1  2020-01-01 01:15:00              NaN

(2731946, 4)

In [22]:
print(weather.head())
weather.shape

   CampusKey            Timestamp  ApparentTemperature  AirTemperature  \
0          1  2020-01-01 00:00:00            13.666667       13.880000
1          1  2020-01-01 00:15:00            13.206667       13.666667
2          1  2020-01-01 00:30:00            12.840000       13.553333
3          1  2020-01-01 00:45:00            12.113333       13.506667
4          1  2020-01-01 01:00:00            11.946667       13.260000

   DewPointTemperature  RelativeHumidity  WindSpeed  WindDirection
0             8.960000         72.400000   0.000000     188.133333
1             9.040000         73.466667   1.200000     203.866667
2             9.053333         74.000000   2.520000     222.800000
3             9.100000         74.466667   5.986667     231.133333
4             9.266667         76.533333   5.946667     247.866667

(371769, 8)

Now I want to visualise the Solar Dataset
1)Which Site and which Panels wrt What Time produce Solar?

In [19]:
solar['Timestamp']=pd.to_datetime(solar['Timestamp'])

No need to visualise since I have understood the dataset

Kaggle #Summary is helpful to understand the data

Next step:- Clean the data so that we can merge the datasets(which I believe we should do)
and thereafter train the model(easier part)

Solution:- Identify problems in both the datasets

For now only:- Site 1
Merge on Weather Data?

In [25]:
site1=solar[solar["SiteKey"]==1]
#Time series is odered

In [26]:
site1[site1['SolarGeneration'].isna()].head()

   CampusKey  SiteKey           Timestamp  SolarGeneration
0          2        1 2020-01-01 00:15:00              NaN
1          2        1 2020-01-01 00:30:00              NaN
2          2        1 2020-01-01 00:45:00              NaN
3          2        1 2020-01-01 01:00:00              NaN
4          2        1 2020-01-01 01:15:00              NaN

In [27]:
site1[site1['SolarGeneration'].isna()].head()

   CampusKey  SiteKey           Timestamp  SolarGeneration
0          2        1 2020-01-01 00:15:00              NaN
1          2        1 2020-01-01 00:30:00              NaN
2          2        1 2020-01-01 00:45:00              NaN
3          2        1 2020-01-01 01:00:00              NaN
4          2        1 2020-01-01 01:15:00              NaN

In [32]:
site1.isna().sum()

CampusKey              0
SiteKey                0
Timestamp              0
SolarGeneration    41746
dtype: int64

In [33]:
(site1['SolarGeneration'].isna().sum() / len(site1)) * 100

np.float64(52.6305172783318)

In [34]:
site1['hour'] = site1['Timestamp'].dt.hour

nan_rows = site1[site1['SolarGeneration'].isna()]

print(nan_rows['hour'].value_counts().sort_index())

hour
0     3308
1     3320
2     3321
3     3323
4     3321
5     3316
6     2730
7      987
8      115
9       84
10      68
11     143
12     315
13     362
14     222
15      73
16      53
17     657
18    1471
19    1813
20    2896
21    3289
22    3283
23    3276
Name: count, dtype: int64

C:\Users\vihaa\AppData\Local\Temp\ipykernel_94256\2822155713.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  site1['hour'] = site1['Timestamp'].dt.hour